baseURL: www.example.com
languageCode: pt-br
title: ALTIS CONSULTORIA
theme: hugo-serif-theme
module:
  hugoVersion:
    extended: yes
    min: 0.55.0
params:
  footer:
    copyright_text: Free Hugo theme by <a class="zerostatic" href="https://www.zerostatic.io">www.zerostatic.io</a>
  google_analytics_id: ''
  google_tag_manager_id: ''
  homepage:
    show_contact_box: yes
    show_services_button: yes
  logo:
    alt: ALTIS CONSULTORIA
    desktop: images/logo/logo.svg
    desktop_height: 36px
    mobile: images/logo/logo-mobile.svg
    mobile_height: 36px
  seo:
    meta_twitter_creator: '@hcostax'
    meta_twitter_site: '@hcostax'
  team:
    summary_large_truncate: 120
menu:
  footer:
    - name: Início
      url: /
      weight: 1
    - name: Contato
      url: /contact/
      weight: 2
  main:
    - name: Serviços
      url: /services/
      weight: 1
    - name: Team
      url: /team/
      weight: 2
    - name: About
      url: /about/
      weight: 3
    - name: Contact
      url: /contact/
      weight: 4
